services:
  backend:
    build:
      context: ./backend
    container_name: piposint-back
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
    container_name: piposint-front
    ports:
      - "5001:4173"
  service_ot:
    build:
      context: ./overpass-turbo
    container_name: piposint-service_ot
    ports:
      - "5002:5173"