services:
  nginx:
    build:
      context: ./nginx
    container_name: piposint-nginx
    ports:
      - "5000:443"
    networks:
      - network
  backend:
    build:
      context: ./backend
    container_name: piposint-back
    networks:
      - network
  frontend:
    build:
      context: ./frontend
    container_name: piposint-front
    depends_on:
      - backend
    networks:
      - network
  service_ot:
    build:
      context: ./overpass-turbo
    container_name: piposint-service_ot
    networks:
      - network
networks:
  network: