services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: piposint_back
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    #links:
    #  - front
    env_file:
      - .env